name: Node.js CI/CD

on:
  push:
    branches: [main] # Trigger on push to the main branch
  pull_request:
    branches: [main] # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use Ubuntu for better compatibility with Docker

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Use Node.js version 18 (or your preferred version)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

      # Step 5: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 6: Configure Docker to use Google Artifact Registry
      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # Step 7: Build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/rivve-backend/rivve-backend
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Step 8: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy rivve-backend \
            --image=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/rivve-backend/rivve-backend \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated
